# on: push es un evento que desencadena el flujo de trabajo cuando se realiza push
# a la rama del repositorio (master o main) en la que se encuentra el archivo YML 
on: push
# jobs: en este bloque define los trabajos que se ejecutarán como parte del flujo de trabajo
# en este caso hay un solo trabajo llamado first-job
jobs:
    # es el nombre del trabajo que se ejecutará, nota se pueden tener multiples flujos de trabajo
    first-job: 
        # especifica el entorno en el que se ejecutará el trabajo
        # en este caso el trabajo se ejecutará en la última versión de Windows.
        runs-on: ubuntu-latest
        container: node:14.6.0
        # steps: aquí se definen las tareas que se ejecutarán como parte del trabajo.
        # cada paso representa una tarea específica que se realizará en el entorno especificado.
        steps:
            - run: node --version 
            - run: npm --version 